version: '3'

services:
  web:
    build: .
    ports:
      - "4567:4567"
      - "9394:9394"
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - SHELL=/bin/bash
    env_file:
      - .env
      - .env-dev-values

volumes:
  gem_cache:
