version: '3.8'

services:
  web:
    build: 
      context: .
      target: development
    ports:
      - "4567:4567"
      - "9394:9394"
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - SHELL=/bin/bash
    env_file:
      - .env
      - env.development

volumes:
  gem_cache:
